title: Merlot theme
description: Merlot is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-merlot


remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme